[project]
name = 'wordchain'
description = 'WordChain: On-Chain Vocabulary Challenge - Learn-to-Earn Game'
authors = []
telemetry = false
cache_dir = './.clarinet'
requirements = []
[contracts.stacks_game]
path = 'contracts/stacks_game.clar'
clarity_version = 3
epoch = 'latest'

[contracts.tic-tac-toe]
path = 'contracts/tic-tac-toe.clar'
clarity_version = 2
epoch = '2.4'

[contracts.tic-tac-toe-improved]
path = 'contracts/tic-tac-toe-improved.clar'
clarity_version = 2
epoch = '2.4'

[contracts.wordchain-core]
path = 'contracts/wordchain-core.clar'
clarity_version = 2
epoch = '2.4'
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
